## This is a copy of run/Dockerfile, but it inherits from pwighton/fs-baby-base
## for FSL
##-------------------------------------------------
# FROM neurodebian:xenial
FROM pwighton/fs-baby-base

RUN apt-get update && \
    apt-get install -y \
      bc \
      binutils \
      libgomp1 \
      net-tools \
      perl \
      psmisc \
      sudo \
      tar \
      tcsh \
      unzip \
      uuid-dev \
      vim-common

# Mount point for FreeSurfer binaries (result of compilation)
VOLUME /fs-bin
ENV FREESURFER_HOME=/fs-bin
ENV PATH $FREESURFER_HOME/bin:$PATH

# Mount point for $SUBJECTS_DIR dir
VOLUME /fs-sub
ENV SUBJECTS_DIR /fs-sub

# Mount point for $FS_INFANT_MODEL
VOLUME /fs-infant-model
ENV FS_INFANT_MODEL /fs-infant-model

# todo: make work with neurodocker
# Add entrypoint script for licence key management
# ADD entrypoint.freesurfer-run.bash /usr/local/bin/entrypoint.bash
# RUN chmod +rx /usr/local/bin/entrypoint.bash
# ENTRYPOINT ["/usr/local/bin/entrypoint.bash"]

# ENV vals from https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/infant/Dockerfile
ENV OS Linux
ENV FREESURFER $FREESURFER_HOME
ENV FS_OVERRIDE 0
ENV PERL5LIB $FREESURFER_HOME/mni/share/perl5
ENV LOCAL_DIR $FREESURFER_HOME/local
ENV FSFAST_HOME $FREESURFER_HOME/fsfast
ENV FMRI_ANALYSIS_DIR $FREESURFER_HOME/fsfast
ENV FSF_OUTPUT_FORMAT nii.gz
ENV MINC_BIN_DIR $FREESURFER_HOME/mni/bin
ENV FUNCTIONALS_DIR $FREESURFER_HOME/sessions
ENV MINC_LIB_DIR $FREESURFER_HOME/mni/lib
ENV MNI_DIR $FREESURFER_HOME/mni
ENV MNI_DATAPATH $FREESURFER_HOME/mni/data
ENV MNI_PERL5LIB $FREESURFER_HOME/mni/share/perl5
ENV FIX_VERTEX_AREA ""
ENV FSLOUTPUTTYPE NIFTI_GZ

# To supress a `Could not set locale` error when `mri_convert` is run in recon-all
ENV FS_DISABLE_LANG 1

# Just in case
# https://github.com/freesurfer/freesurfer/issues/776
ENV FS_TIME_ALLOW 0

# To get nu_correct in the PATH (fs-pkg needs to be vol mounted for now)
ENV PATH /fs-pkg/mni/current/bin:$PATH

# To supress the error:
#  `error: fspython has not been configured correctly - $FREESURFER_HOME/python/bin/python3 does not exist`
CMD rm -f $FREESURFER_HOME/python/bin/python3 && \
    ln -s `which python` $FREESURFER_HOME/python/bin/python3
    
# MODEL CONFIG
# -------------------------------------------------------

# Skull stripping model files
# The code will look for models at `$FREESURFER_HOME/average/sscnn_skullstripping`
# And they are located inside our infant model at `$FS_INFANT_MODEL/sscnn_skullstrip`
CMD \
  ln -s $FS_INFANT_MODEL/sscnn_skullstrip/cor_sscnn.h5 $FREESURFER_HOME/average/sscnn_skullstripping/cor_sscnn.h5 && \
  ln -s $FS_INFANT_MODEL/sscnn_skullstrip/ax_sscnn.h5 $FREESURFER_HOME/average/sscnn_skullstripping/ax_sscnn.h5 && \
  ln -s $FS_INFANT_MODEL/sscnn_skullstrip/sag_sscnn.h5 $FREESURFER_HOME/average/sscnn_skullstripping/sag_sscnn.h5 

# Env vars set in 
# `freesurfer/average/CNYBCH/README` in 
# `https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/infant/freesurfer-linux-centos7_x86_64-infant.tar.gz`
ENV CNYBCH_TEMPLATE_SUBJECTS_DIR $FS_INFANT_MODEL/CNYBCH
ENV CNYBCH_SUBJECTS "Template1 Template2 Template3 Template4 Template5 Template6 Template7 Template8 Template9 Template10 Template11 Template12 Template13 Template14 Template15 Template16 Template17 Template18 Template19 Template20 Template21 Template22 Template23 Template24 Template25 Template26"
# age at MRI scan (mo)
ENV CNYBCH_AGES "9 7 6 5 18 12 0 0 3 8 10 10 18 4 2 14 3 16 0 12 0 15 5 17 16 0"
ENV CNYBCH_GMWM_SUBJECTS "Template5 Template6 Template8 Template10 Template13 Template18 Template20 Template22"
# mo
ENV CNYBCH_GMWM_AGES "18 12 0 8 18 16 12 15"
ENV CNYBCH_NEONATES "Template7 Template8 Template19 Template21 Template26"
# days (first two computed from weeks)
ENV CNYBCH_NEONATEAGES "3 4 1 2 4"
ENV CNYBCH_AROUNDONE "Template11 Template12 Template6 Template20 Template16"
#mo
ENV CNYBCH_AROUNDONEAGES "10 10 12 12 14"