# Neurodocker generated image used to install FSL, python, etc
# See make target "fs-baby-base-dockerfile"
FROM pwighton/fs-baby-base

USER root

RUN apt-get update && \
    apt-get install -y \
      bc \
      binutils \
      coreutils \
      libgomp1 \
      net-tools \
      perl \
      psmisc \
      sudo \
      tar \
      tcsh \
      unzip \
      uuid-dev \
      vim-common

# To force the activation of the freesurfer conda env created via neurodocker
# in `pwighton/fs-baby-base`, for the subsequent pip install commands
ENV CONDA_DEFAULT_ENV=freesurfer
ENV CONDA_PROMPT_MODIFIER=(freesurfer) 
ENV PATH=/opt/miniconda-latest/envs/freesurfer/bin:/opt/miniconda-latest/condabin:$PATH
ENV CONDA_PREFIX=/opt/miniconda-latest/envs/freesurfer
# Install required python packages
COPY requirements.txt /tmp/requirements.txt
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r /tmp/requirements.txt 

# Install niftyreg
#RUN cd /opt && \
#    curl -sSL --retry 5 \
#        https://sourceforge.net/projects/niftyreg/files/nifty_reg-1.3.9/NiftyReg-1.3.9-Linux-x86_64-Release.tar.gz/download \
#        | tar -xz
#ENV PATH=/opt/NiftyReg-1.3.9-Linux-x86_64-Release/bin:$PATH
#ENV LD_LIBRARY_PATH=/opt/NiftyReg-1.3.9-Linux-x86_64-Release/lib:$LD_LIBRARY_PATH

# MOUNT POINTS 
# -------------------------------------------------------

# Mount point for FreeSurfer binaries (result of compilation)
VOLUME /fs-bin
ENV FREESURFER_HOME=/fs-bin
ENV PATH $FREESURFER_HOME/bin:$PATH

# Mount point for $SUBJECTS_DIR dir
VOLUME /fs-sub
ENV SUBJECTS_DIR /fs-sub

# Mount point for $FS_INFANT_MODEL
VOLUME /fs-infant-model
ENV FS_INFANT_MODEL /fs-infant-model

# Mount point for NiftyReg Binaries
VOLUME /nr-bin
ENV NR_BIN /nr-bin/bin
ENV PATH $NR_BIN:$PATH

# From https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/infant/Dockerfile
# -------------------------------------------------------
ENV OS Linux
ENV FREESURFER $FREESURFER_HOME
ENV FS_OVERRIDE 0
ENV PERL5LIB $FREESURFER_HOME/mni/share/perl5
ENV LOCAL_DIR $FREESURFER_HOME/local
ENV FSFAST_HOME $FREESURFER_HOME/fsfast
ENV FMRI_ANALYSIS_DIR $FREESURFER_HOME/fsfast
ENV FSF_OUTPUT_FORMAT nii.gz
ENV MINC_BIN_DIR $FREESURFER_HOME/mni/bin
ENV FUNCTIONALS_DIR $FREESURFER_HOME/sessions
ENV MINC_LIB_DIR $FREESURFER_HOME/mni/lib
ENV MNI_DIR $FREESURFER_HOME/mni
ENV MNI_DATAPATH $FREESURFER_HOME/mni/data
ENV MNI_PERL5LIB $FREESURFER_HOME/mni/share/perl5
ENV FIX_VERTEX_AREA ""
ENV FSLOUTPUTTYPE NIFTI_GZ

# To supress a `Could not set locale` error when `mri_convert` is run in recon-all
ENV FS_DISABLE_LANG 1

# Just in case
# https://github.com/freesurfer/freesurfer/issues/776
ENV FS_TIME_ALLOW 0

# To get nu_correct in the PATH (fs-pkg needs to be vol mounted for now)
ENV PATH /fs-pkg/mni/current/bin:$PATH

# MODEL CONFIG
# -------------------------------------------------------

# Env vars set in 
# `freesurfer/average/CNYBCH/README` in 
# `https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/infant/freesurfer-linux-centos7_x86_64-infant.tar.gz`
ENV CNYBCH_TEMPLATE_SUBJECTS_DIR $FS_INFANT_MODEL/CNYBCH
ENV CNYBCH_SUBJECTS "Template1 Template2 Template3 Template4 Template5 Template6 Template7 Template8 Template9 Template10 Template11 Template12 Template13 Template14 Template15 Template16 Template17 Template18 Template19 Template20 Template21 Template22 Template23 Template24 Template25 Template26"
# age at MRI scan (mo)
ENV CNYBCH_AGES "9 7 6 5 18 12 0 0 3 8 10 10 18 4 2 14 3 16 0 12 0 15 5 17 16 0"
ENV CNYBCH_GMWM_SUBJECTS "Template5 Template6 Template8 Template10 Template13 Template18 Template20 Template22"
# mo
ENV CNYBCH_GMWM_AGES "18 12 0 8 18 16 12 15"
ENV CNYBCH_NEONATES "Template7 Template8 Template19 Template21 Template26"
# days (first two computed from weeks)
ENV CNYBCH_NEONATEAGES "3 4 1 2 4"
ENV CNYBCH_AROUNDONE "Template11 Template12 Template6 Template20 Template16"
#mo
ENV CNYBCH_AROUNDONEAGES "10 10 12 12 14"


# ENTRYPOINT
# -------------------------------------------------------

# Add entrypoint script for licence key management and runtime config
ADD entrypoint.freesurfer-run.bash /usr/local/bin/entrypoint.bash
RUN chmod +rx /usr/local/bin/entrypoint.bash
ENTRYPOINT ["/usr/local/bin/entrypoint.bash"]
