FROM rockylinux:8.9

WORKDIR /root

# Install:
#  - wget to grab FreeSurfer install files
#  - findutils to run find inside the conainer (quality of life)
#  - libgomp, needed for FreeSurfer
#  - mesa-dri-drivers, needed by FreeView for software OpenGL rendering
RUN dnf -y update && \
    dnf -y install wget findutils libgomp procps-ng libXt libXext ncurses-compat-libs unzip python3 mesa-dri-drivers

# Install FreeSurfer
# - see: https://surfer.nmr.mgh.harvard.edu/fswiki/ReleaseNotes
RUN wget --progress=bar:force:noscroll https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/8.2.0/freesurfer-Rocky8-8.2.0-1.x86_64.rpm && \
    dnf install -y freesurfer-Rocky8-8.2.0-1.x86_64.rpm && \
    wget --progress=bar:force:noscroll https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/8.2.0/fs820_updates.sh && \
    yes y | tr -d '\n' | FREESURFER_HOME=/usr/local/freesurfer/8.2.0-1 bash fs820_updates.sh && \
    dnf clean all && \
    rm freesurfer-Rocky8-8.2.0-1.x86_64.rpm && \
    rm fs820_updates.sh && \
    rm -rf ./default

# Set the FreeSurfer-related environment variables.  Everything other than
# FREESURFER_HOME and SUBJECTS_DIR is what would get set by running
# `source $FREESURFER_HOME/SetUpFreeSurfer.sh`
ENV FREESURFER_HOME=/usr/local/freesurfer/8.2.0-1 \
    SUBJECTS_DIR=/usr/local/freesurfer/8.2.0-1/subjects \
    FIX_VERTEX_AREA= \
    FMRI_ANALYSIS_DIR=/usr/local/freesurfer/8.2.0-1/fsfast \
    FREESURFER_HOME_FSPYTHON=/usr/local/freesurfer/8.2.0-1 \
    FREESURFER=/usr/local/freesurfer/8.2.0-1 \
    FSFAST_HOME=/usr/local/freesurfer/8.2.0-1/fsfast \
    FSF_OUTPUT_FORMAT=nii.gz \
    FS_OVERRIDE=0 \
    FUNCTIONALS_DIR=/usr/local/freesurfer/8.2.0-1/sessions \
    LOCAL_DIR=/usr/local/freesurfer/8.2.0-1/local \
    MINC_BIN_DIR=/usr/local/freesurfer/8.2.0-1/mni/bin \
    MINC_LIB_DIR=/usr/local/freesurfer/8.2.0-1/mni/lib \
    MNI_DATAPATH=/usr/local/freesurfer/8.2.0-1/mni/data \
    MNI_DIR=/usr/local/freesurfer/8.2.0-1/mni \
    MNI_PERL5LIB=/usr/local/freesurfer/8.2.0-1/mni/share/perl5 \
    OS=Linux \
    PATH=/usr/local/freesurfer/8.2.0-1/bin:/usr/local/freesurfer/8.2.0-1/fsfast/bin:/usr/local/freesurfer/8.2.0-1/tktools:/usr/local/freesurfer/8.2.0-1/mni/bin:${PATH} \
    PERL5LIB=/usr/local/freesurfer/8.2.0-1/mni/share/perl5

# Install Matlab Runtime R2012b
# - See: https://surfer.nmr.mgh.harvard.edu/fswiki/rel7downloads/rel8notes
RUN FREESURFER_HOME=$FREESURFER_HOME $FREESURFER_HOME/bin/fs_install_mcr R2019b

# Not setting LD_LIBRARY_PATH by default because this breaks curl
# ENV LD_LIBRARY_PATH=$FREESURFER_HOME/MCRv97/runtime/glnxa64:$FREESURFER_HOME/MCRv97/bin/glnxa64:$FREESURFER_HOME/MCRv97/sys/os/glnxa64:$FREESURFER_HOME/MCRv97/extern/bin/glnxa64
