FROM rockylinux:8

WORKDIR /root

# Install:
#  - wget to grab FreeSurfer install files
#  - findutils to run find inside the conainer (quality of life)
#  - libgomp, needed for FreeSurfer
RUN dnf -y update && \
    dnf -y install wget findutils libgomp

# Install FreeSurfer
RUN wget --progress=bar:force:noscroll https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/8.0.0/freesurfer-Rocky8-8.0.0-1.x86_64.rpm && \
    dnf install -y freesurfer-Rocky8-8.0.0-1.x86_64.rpm && \
    dnf clean all && \
    rm freesurfer-Rocky8-8.0.0-1.x86_64.rpm

# Set the FreeSurfer-related environment variables.  Everything other than
# FREESURFER_HOME and SUBJECTS_DIR is what would get set by running
# `source $FREESURFER_HOME/SetUpFreeSurfer.sh`
ENV FREESURFER_HOME=/usr/local/freesurfer/8.0.0-1 \
    SUBJECTS_DIR=/usr/local/freesurfer/8.0.0-1/subjects \
    FIX_VERTEX_AREA= \
    FMRI_ANALYSIS_DIR=/usr/local/freesurfer/8.0.0-1/fsfast \
    FREESURFER_HOME_FSPYTHON=/usr/local/freesurfer/8.0.0-1 \
    FREESURFER=/usr/local/freesurfer/8.0.0-1 \
    FSFAST_HOME=/usr/local/freesurfer/8.0.0-1/fsfast \
    FSF_OUTPUT_FORMAT=nii.gz \
    FS_OVERRIDE=0 \
    FUNCTIONALS_DIR=/usr/local/freesurfer/8.0.0-1/sessions \
    LOCAL_DIR=/usr/local/freesurfer/8.0.0-1/local \
    MINC_BIN_DIR=/usr/local/freesurfer/8.0.0-1/mni/bin \
    MINC_LIB_DIR=/usr/local/freesurfer/8.0.0-1/mni/lib \
    MNI_DATAPATH=/usr/local/freesurfer/8.0.0-1/mni/data \
    MNI_DIR=/usr/local/freesurfer/8.0.0-1/mni \
    MNI_PERL5LIB=/usr/local/freesurfer/8.0.0-1/mni/share/perl5 \
    OS=Linux \
    PATH=/usr/local/freesurfer/8.0.0-1/bin:/usr/local/freesurfer/8.0.0-1/fsfast/bin:/usr/local/freesurfer/8.0.0-1/tktools:/usr/local/freesurfer/8.0.0-1/mni/bin:${PATH} \
    PERL5LIB=/usr/local/freesurfer/8.0.0-1/mni/share/perl5

# Patch freesurfer
RUN wget --progress=bar:force:noscroll https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/8.0.0/fs8_updates.sh && \
    source ./fs8_updates.sh && \
    rm fs8_updates.sh
