FROM pwighton/petsurfer:7.2.0

RUN apt-get update -qq \
    && apt-get install -y -q --no-install-recommends graphviz git

RUN git clone --branch main https://github.com/openneuropet/derivatives.git /opt/openneuropet-derivatives

RUN git clone --branch add_pet_freesurfer https://github.com/mnoergaard/nipype.git /opt/nipype \
    && cd /opt/nipype \
    && pip install -e .

# Using this until tweaks are merged
RUN git clone --branch 20211130-merge https://github.com/pwighton/petpipeline.git /opt/petpipeline \
    && cd /opt/petpipeline \
    && pip install -e .
# After merge, revert to this    
#RUN git clone --branch main https://github.com/openneuropet/petpipeline.git /opt/petpipeline \
#    && cd /opt/petpipeline \
#    && pip install -e .

# rename the build-stamp because it throws errors when nipype tries to parse it
# todo: fix
RUN mv ${FREESURFER_HOME}/build-stamp.txt ${FREESURFER_HOME}/build-stamp-tmp.txt
